### ISSUE TITLE
Working with LLFF and Tanks and temples scenes

### ISSUE THREAD

**Issue by hanyucc** [akanimax/thr3ed_atom#19]
I saw that there was a script to convert the NeRF blender dataset into the format required by ReLU fields. How difficult would it be to create something similar for the LLFF and Tanks and temples scenes that NeRF also uses? They seems to be in pretty different formats, so I'm wondering if you have any experience working with those. Thanks!

**Comment by akanimax** [comment]
Hi @hanyucc, 
Indeed, LLFF and T&T are quite different from the use-case of ReLU-Fields. If you wish to use this code-base for LLFF, then you'll have to implement the NDC ray-sampling here [see here](https://github.com/bmild/nerf/blob/master/run_nerf_helpers.py#L143) for reference.  I suppose the cameras for LLFF could be loaded in this code-base, just make sure that the conventions match. I use the conventions of OpenGL (same as NERF).

In case of T&T, I don't think the dense-grid of ReLU fields would be able to represent all the details of the unbounded scenes properly. I'd suggest Plenoxels (which is sparse relu-fields) for this use-case. 

The main use-case of ReLU-fields is sort-of pre-filtering of synthetic 3D assets. 

Hope this helps!
